org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.18.2
minecraft_version_range=[1.18.2,1.19)
forge_version=40.2.17
forge_version_range=[40,41)
loader_version_range=[40,41)
rei_version=8.4.778

mod_id=reiexport
mod_name=REI Recipe Exporter
mod_license=MIT
mod_version=1.0.52
mod_group_id=com.recipetree.reiexport
mod_authors=josiahmann
mod_description=Exports exact REI item and recipe renders plus graph data for Minecraft Recipe Tree.
